import dayjs from 'dayjs'
export const NUMBER_SCHEDULE = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

export const initialFormDataSetupSchedule = {
  idcmd: 'set_schedule',
  date_event: dayjs().format('YYYY-MM-DD'),
  number_schedule: 0,
  output: '1',
  on1: '',
  off1: '',
  on2: '',
  off2: '',
  on3: '',
  off3: '',
  on4: '',
  off4: '',
  on5: '',
  off5: '',
  on6: '',
  off6: '',
  on7: '',
  off7: '',
  on8: '',
  off8: '',
  on9: '',
  off9: '',
  on10: '',
  off10: '',
  on11: '',
  off11: '',
  on12: '',
  off12: '',
}
